services:
  server:
    build: .
    ports:
      - "5002:5002"
    env_file:
      - .env
    depends_on:
      - grobid
    restart: unless-stopped

  grobid:
    image: grobid/grobid:0.8.2-crf
    ports:
      - "8070:8070"
    restart: unless-stopped
